from typing import Any

from pydantic import BaseModel, Field


class AnalysisResponse(BaseModel):
    status: str = Field(
        ...,
        description="Request status",
        example="success",
    )
    summary: dict[str, Any] = Field(
        ...,
        description="Business summary generated by the analytics engine",
    )
    executive_report: str = Field(
        ...,
        description="AI-generated executive business report",
    )
    metrics: dict[str, Any] = Field(
        ...,
        description="Detailed analytics and KPI results",
    )
